### ISSUE TITLE
Slimmer crashes when starting to play next track in an album

### ISSUE THREAD

**Issue by njansens** [terba/slimmer#13]
When playing an album using the Tidal (streaming service) Plugin on LMS server, as soon as a new song starts, the display goes blank.
When I manually select a new song in the album, this does not happen, and everything keeps running.
Tried re-installing everything, but the behavior stays the same.
Tried to exclude as many influences as possible, so also removed the DAC, and changed the slimmer.conf options to have no input from pikeyd.
Unfortunately to no avail.
Ran the 'top' command, to see if slimmer was still running: It was not.
I can manually restart slimmer (command line), and then it works again. Until the start of a new track: slimmer crashes.
Note: this happens using the Tidal Plugin, playing albums from a a music directory under LMS works fine.

**Comment by terba** [comment]
Please stop the slimmer daemon and try to run it in the foreground from an ssh session in verbose mode:
```bash
sudo /usr/local/etc/init.d/slimmer stop
source /usr/local/etc/slimmer.conf
slimmer -v $OPTIONS
```
Post the output from the crash. Maybe we can see more.

**Comment by njansens** [comment]
So this is what I see happening. Please also not I changed the issue: it only happens using the Tidal music streaming plugin. Hope this helps!

Regards, 
Niels

> tc@piCorePlayer:~$ sudo /usr/local/etc/init.d/slimmer stop
Stopping LMS (slimserver) user interface controller: slimmer...
tc@piCorePlayer:~$ source /usr/local/etc/slimmer.conf
tc@piCorePlayer:~$ slimmer -v $OPTIONS
Configuration:
  LMS: 192.168.10.16:9002
  LCDd: localhost:13666
  PlayerId (MAC): b8:27:eb:54:04:2a
  Input device: /dev/pikeyd
Connected to LCDd (Version: 0.5dev, Protocol: 0.3, Width: 20, Height: 4, Char width: 5, Char height: 8)
terminate called after throwing an instance of 'Json::LogicError'
  what():  Value is not convertible to float.
Aborted
tc@piCorePlayer:~$

**Comment by njansens** [comment]
Not sure if you want to dive into this, since you may find it a 'particular' case, using the Tidal streaming plugin. I can also imagine it is difficult to troubleshoot if you do not have access to this service.
If you want however, I can give you access to my LMS, with the Tidal plugin so you can hook up your picoreplayer and slimmer remotely to see what is happening.
Just let me know and I'll be happy to give you the ip address.

**Comment by terba** [comment]
No problem, I think it will be easy to fix. Tomorrow from 08:00 till 15:00 (CET) I can look into it at any time. Please send the IP and port via email to terenyi@freemail.hu if you set it up tomorrow.

**Comment by terba** [comment]
The problem is that at the end of a track LMS responds an invalid position of the current track:
While playing it sends a correct position: `"time" : 270.78303709602397`
But at the end of the track it sends:   `"time" : "271"` which is not a number value but a character data (enclosed in double quotes).
Slimmer dies at parsing that value.

I fixed that in Slimmer, it will not die on this kind of problems. But I think this should be reported to the maintainer of the Tidal plugin.

I will publish the fix and compile a new release bundle today.
