### ISSUE TITLE
Slimmer don't compile on Debian 9 with pixel raspbian dessktop

### ISSUE THREAD

**Issue by droidboxma** [terba/slimmer#32]
Hey Balázs.

I have another little "make" problem on an Raspi 2 with the new Raspbian Pixel Desktop with Debian 9 Scretch:

`$ make
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/slimmer/slimmer-build
Scanning dependencies of target slimmer
[  4%] Building CXX object CMakeFiles/slimmer.dir/Button.cpp.o
[  8%] Building CXX object CMakeFiles/slimmer.dir/Config.cpp.o
[ 12%] Building CXX object CMakeFiles/slimmer.dir/Controller.cpp.o
[ 16%] Building CXX object CMakeFiles/slimmer.dir/MenuItem.cpp.o
[ 20%] Building CXX object CMakeFiles/slimmer.dir/Player.cpp.o
[ 24%] Building CXX object CMakeFiles/slimmer.dir/Screen.cpp.o
[ 28%] Building CXX object CMakeFiles/slimmer.dir/ScreenError.cpp.o
[ 32%] Building CXX object CMakeFiles/slimmer.dir/ScreenMenu.cpp.o
[ 36%] Building CXX object CMakeFiles/slimmer.dir/ScreenNowPlaying.cpp.o
[ 40%] Building CXX object CMakeFiles/slimmer.dir/ScreenVolume.cpp.o
[ 44%] Building CXX object CMakeFiles/slimmer.dir/Server.cpp.o
[ 48%] Building CXX object CMakeFiles/slimmer.dir/json/jsoncpp.cpp.o
[ 52%] Building CXX object CMakeFiles/slimmer.dir/jsonrpccpp/client/batchcall.cpp.o
[ 56%] Building CXX object CMakeFiles/slimmer.dir/jsonrpccpp/client/batchresponse.cpp.o
[ 60%] Building CXX object CMakeFiles/slimmer.dir/jsonrpccpp/client/client.cpp.o
[ 64%] Building CXX object CMakeFiles/slimmer.dir/jsonrpccpp/client/connectors/httpclient.cpp.o
[ 68%] Building CXX object CMakeFiles/slimmer.dir/jsonrpccpp/client/rpcprotocolclient.cpp.o
[ 72%] Building CXX object CMakeFiles/slimmer.dir/jsonrpccpp/common/errors.cpp.o
[ 76%] Building CXX object CMakeFiles/slimmer.dir/jsonrpccpp/common/exception.cpp.o
[ 80%] Building CXX object CMakeFiles/slimmer.dir/jsonrpccpp/common/procedure.cpp.o
[ 84%] Building CXX object CMakeFiles/slimmer.dir/jsonrpccpp/common/specificationparser.cpp.o
[ 88%] Building CXX object CMakeFiles/slimmer.dir/jsonrpccpp/common/specificationwriter.cpp.o
[ 92%] Building CXX object CMakeFiles/slimmer.dir/main.cpp.o
In file included from /usr/local/src/slimmer/main.cpp:28:0:
/usr/local/src/slimmer/libev/ev.c:1825:31: warning: ‘ev_default_loop_ptr’ initialized and declared ‘extern’
   EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                               ^~~~~~~~~~~~~~~~~~~
[ 96%] Building CXX object CMakeFiles/slimmer.dir/CMakeFiles/3.7.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
[100%] Linking CXX executable slimmer
CMakeFiles/slimmer.dir/CMakeFiles/3.7.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o (symbol from plugin): In function `info_arch':
(.text+0x0): multiple definition of `main'
CMakeFiles/slimmer.dir/main.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/slimmer.dir/build.make:692: recipe for target 'slimmer' failed
make[2]: *** [slimmer] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/slimmer.dir/all' failed
make[1]: *** [CMakeFiles/slimmer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`
Can you help?

Regards Markus

**Comment by terba** [comment]
Hi! This has to do with the CMake system on your machine. It compiles two ```main``` functions, but there can be only one. Slimmer only contains one ```main```. Try to find the other one in the build directory and find the cause, why it exists.

**Comment by droidboxma** [comment]
Hi

You can remove my question. I find the error in my script. Sorry for the trouble.

/MA
