### ISSUE TITLE
Update to "Building a player"

### ISSUE THREAD

**Issue by newface69** [terba/slimmer#34]
I have use your post "Building a player" and it works fine.
I have use a Zero W.
But looking at the Issues it looks like you have made updates to the software, and I don't see them in the version you refers to in your post (slimmer version 1.2.1).
Would it be possible to update the "cd /tmp && wget https://github.com/terba/slimmer/releases/download/v1.2.1/slimmer-bundle.tar.bz2" to current version?

**Comment by terba** [comment]
Hi! 1.2.1 is the latest release. The changes you mentioned are only available in the source code repository. I will make a new release later, when I'm ready with some new features. See milestone 2.0 here in the issues of Slimmer.

**Comment by newface69** [comment]
Thanks  for your reply
Im looking forward for  the new release




Den 7 jan. 2018 8:10 PM skrev "Terényi, Balázs" <notifications@github.com>:
